# Generated by Django 2.0 on 2019-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgName', models.CharField(default='', max_length=256, verbose_name='文件名')),
                ('imgMd5', models.CharField(max_length=128, verbose_name='MD5值')),
                ('imgType', models.CharField(max_length=32, verbose_name='类型')),
                ('imgSize', models.IntegerField(verbose_name='大小')),
                ('imgPath', models.CharField(max_length=128, verbose_name='图片路径')),
                ('imgCreated', models.CharField(default='2019-12-09 19:57:38', max_length=64)),
                ('imgUpdated', models.CharField(default='2019-12-09 19:57:38', max_length=64)),
            ],
        ),
    ]
